### ISSUE TITLE
Please add user manual

### ISSUE THREAD

**Issue by binoue** [aNickzz/DashBot#1]
I think this project is very cool and I want to use.

However, there are no docs or README.md and I can not figure out how to use this.
Please add any documents to guide the usage of this program.

Thanks,

**Comment by aNickzz** [comment]
I've added a readme, reopen this if its not clear enough.

**Comment by banban9999** [comment]
Thank you for adding `README.md`

However, [What can it do](https://github.com/aNickzz/DashBot#what-can-it-do) section lacks of exact steps to run this program.

I hope you write more details of how to run this program. 

I can not reopen this issue because I does not have such privileges. Thus  I only comment here.

**Comment by banban9999** [comment]
thx! great documentation!
